Fix settings.lua to use new additions / changes to DarkRP base settings.lua
FPtje/darkrpmodification pull request #163
Opened 2021-08-07 22:41 UTC by liondadev

Pretty much the title.

2021-08-07 22:56 UTC, liondadev commented
Ignore the language changes, I accidently included them in the same PR.

2021-08-08 10:14 UTC, FPtje requested changes
Thanks! Some commentd

2021-08-08 10:14 UTC, FPtje commented on lua/darkrp_config/settings.lua
> -
Why are these newlines removed?

2021-08-08 10:14 UTC, FPtje commented on lua/darkrp_config/settings.lua
> +GM.Config.starverate = 3
Missing newline at end of file

2021-08-08 11:23 UTC, liondadev commented
I dont remember removing those, ill add them back.

2021-08-09 06:16 UTC, merged